SELECT
GETDATE()[TARÝH],
LOGREF,
CODE [MLZM KODU], NAME [MLZM AÇIKLAMASI],
NAME3 [MLZM AÇIKLAMASI2], STGRPCODE [GRUPKODU],
SPECODE2 +'-'+ SPE2 'ÖZELKOD2',
SPECODE3 +'-'+ SPE3 'ÖZELKOD3',
SPECODE4 +'-'+ SPE4 'ÖZELKOD4',
STOK, [BÝRÝM], [BR.FÝYAT], STOK*[BR.FÝYAT] 'TUTAR',
[BF.FATURA], [BF.SARF], 
[BF.ÜRETÝM], [BF.SÝPARÝÞ], 
[BF.DEVÝR], [BF.KART],

CASE
     WHEN [BR.FÝYAT]-[BF.FATURA]=0 THEN 'FATURA ' 
     WHEN [BR.FÝYAT]-[BF.SARF]=0 THEN 'SARF '
     WHEN [BR.FÝYAT]-[BF.ÜRETÝM]=0 THEN 'ÜRETÝM '
     WHEN [BR.FÝYAT]-[BF.SÝPARÝÞ]=0 THEN 'SÝPARÝÞ '
     WHEN [BR.FÝYAT]-[BF.DEVÝR]=0 THEN 'DEVÝR '
     WHEN [BR.FÝYAT]-[BF.KART]=0 THEN 'KART '
ELSE '===== ' END AS [RFR]
, [BF.SATIÞ]
--, [0:AKTÝF] 

FROM
(SELECT ITM.LOGICALREF[LOGREF], ITM.CODE, ITM.NAME, ITM.NAME3, ITM.STGRPCODE, SPECODE2, SPE2.DEFINITION_'SPE2',
SPECODE3, SPE3.DEFINITION_'SPE3',
SPECODE4, SPE4.DEFINITION_'SPE4',
ISNULL(S.STOK,0)'STOK',

CASE

     WHEN P.FÝYAT>0 THEN ISNULL(P.FÝYAT,0) 
     WHEN ISNULL(P.FÝYAT,0)=0 AND G.PRICE>0 THEN ISNULL(G.PRICE,0)  --
     WHEN ISNULL(G.PRICE,0)=0 AND U.PRICE>0 THEN ISNULL(U.PRICE,0)
     WHEN ISNULL(U.PRICE,0)=0 AND R.PRICE>0 THEN ISNULL(R.PRICE,0)
     WHEN ISNULL(R.PRICE,0)=0 AND D.PRICE>0 THEN ISNULL(D.PRICE,0)
     WHEN ISNULL(D.PRICE,0)=0 AND K.PRICE>0 THEN ISNULL(K.PRICE,0)

ELSE ISNULL(K.PRICE,0)+0 END AS [BR.FÝYAT], 

UL.CODE [BÝRÝM],
P.FÝYAT [BF.FATURA], 
G.PRICE [BF.SARF],
U.PRICE [BF.ÜRETÝM],
R.PRICE [BF.SÝPARÝÞ], 
D.PRICE [BF.DEVÝR],
K.PRICE [BF.KART],
L.PRICE [BF.SATIÞ]
-- , , ITM.ACTIVE [0:AKTÝF] 

FROM LG_222_ITEMS ITM
INNER JOIN LG_222_UNITSETL UL ON UL.UNITSETREF=ITM.UNITSETREF AND UL.MAINUNIT=1
LEFT JOIN LG_222_SPECODES SPE2 ON SPE2.SPECODE=ITM.SPECODE2 AND SPE2.SPECODETYPE=1 AND SPE2.SPETYP2=1
LEFT JOIN LG_222_SPECODES SPE3 ON SPE3.SPECODE=ITM.SPECODE3 AND SPE3.SPECODETYPE=1 AND SPE3.SPETYP3=1
LEFT JOIN LG_222_SPECODES SPE4 ON SPE4.SPECODE=ITM.SPECODE4 AND SPE4.SPECODETYPE=1 AND SPE4.SPETYP4=1

OUTER APPLY(SELECT SUM(ONHAND)'STOK' FROM LV_222_01_STINVTOT WHERE  STOCKREF=ITM.LOGICALREF AND INVENNO=-1  --AND DATE_>={FLTDATEBEG(1)} AND DATE_<={FLTDATEEND(1)} 
) AS S
OUTER APPLY(SELECT AVG(PRICE*(STL.UINFO2/CASE WHEN STL.UINFO1=0 THEN 1 ELSE STL.UINFO1 END))'FÝYAT' FROM LG_222_01_STLINE STL WHERE  PRICE <> 0 AND STOCKREF=ITM.LOGICALREF AND TRCODE=1 AND UOMREF=UL.LOGICALREF  --AND DATE_>={FLTDATEBEG(1)} AND DATE_<={FLTDATEEND(1)} 
) AS P
OUTER APPLY(SELECT AVG(PRICE*(STL.UINFO2/CASE WHEN STL.UINFO1=0 THEN 1 ELSE STL.UINFO1 END))'PRICE' FROM LG_222_01_STLINE STL WHERE  PRICE <> 0 AND STOCKREF=ITM.LOGICALREF AND TRCODE IN (12)  AND UOMREF=UL.LOGICALREF-- AND DATE_>={FLTDATEBEG(1)} AND DATE_<={FLTDATEEND(1)}
) AS G
OUTER APPLY(SELECT AVG(PRICE*(STL.UINFO2/CASE WHEN STL.UINFO1=0 THEN 1 ELSE STL.UINFO1 END))'PRICE' FROM LG_222_01_STLINE STL WHERE  PRICE <> 0 AND STOCKREF=ITM.LOGICALREF AND TRCODE IN (13)  AND UOMREF=UL.LOGICALREF --AND DATE_>={FLTDATEBEG(1)} AND DATE_<={FLTDATEEND(1)}
) AS U
OUTER APPLY(SELECT AVG(PRICE*(ORF.UINFO2/CASE WHEN ORF.UINFO1=0 THEN 1 ELSE ORF.UINFO1 END))'PRICE' FROM LG_222_01_ORFLINE ORF WHERE  PRICE <> 0 AND STOCKREF=ITM.LOGICALREF AND TRCODE IN (2)  AND UOMREF=UL.LOGICALREF --AND DATE_>={FLTDATEBEG(1)} AND DATE_<={FLTDATEEND(1)}
) AS R
OUTER APPLY(SELECT AVG(PRICE*(STL.UINFO2/CASE WHEN STL.UINFO1=0 THEN 1 ELSE STL.UINFO1 END))'PRICE' FROM LG_222_01_STLINE STL WHERE  PRICE <> 0 AND STOCKREF=ITM.LOGICALREF AND TRCODE IN (14) AND UOMREF=UL.LOGICALREF
) AS D
OUTER APPLY(SELECT AVG(PRICE)'PRICE' FROM LG_222_PRCLIST PRL WHERE  PRICE <> 0 AND PRL.CARDREF=ITM.LOGICALREF AND UOMREF=UL.LOGICALREF
) AS K
OUTER APPLY(SELECT AVG(PRICE*(STL.UINFO2/CASE WHEN STL.UINFO1=0 THEN 1 ELSE STL.UINFO1 END))'PRICE' FROM LG_222_01_STLINE STL WHERE  PRICE <> 0 AND STOCKREF=ITM.LOGICALREF AND TRCODE IN (8) AND UOMREF=UL.LOGICALREF  --AND DATE_>={FLTDATEBEG(1)} AND DATE_<={FLTDATEEND(1)}
) AS L
WHERE ITM.ACTIVE=0
) AS A





